# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: miler90
google_analytics: miler90
title: miler90

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Miler90

description: Stylish Jekyll Theme
author:
  name: Miler90
  email: 516346496@qq.com
  github: miler90
  bio: Let's Do it!
  email_md5: f469932393622596c1b973acb02f4d31

# rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate