# Permalinks
permalink:           pretty

# Setup
title:               Milker90
tagline:             Go Go Go!
url:                 http://niecpq.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Milker90
  url:               http://niecpq.com
  email:             516346496@qq.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/milker90

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
